services:
  - type: web
    name: tst-brasil-hub
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    preDeployCommand: pnpm db:migrate
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
