DROP TABLE `action_items`;--> statement-breakpoint
DROP TABLE `admin_access_audit`;--> statement-breakpoint
DROP TABLE `certificates`;--> statement-breakpoint
DROP TABLE `client_engagements`;--> statement-breakpoint
DROP TABLE `client_visits`;--> statement-breakpoint
DROP TABLE `companies`;--> statement-breakpoint
DROP TABLE `departments`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `epi_deliveries`;--> statement-breakpoint
DROP TABLE `epi_items`;--> statement-breakpoint
DROP TABLE `epi_requirements`;--> statement-breakpoint
DROP TABLE `epi_returns`;--> statement-breakpoint
DROP TABLE `inspection_template_items`;--> statement-breakpoint
DROP TABLE `inspection_templates`;--> statement-breakpoint
DROP TABLE `inspections`;--> statement-breakpoint
DROP TABLE `job_roles`;--> statement-breakpoint
DROP TABLE `materials`;--> statement-breakpoint
DROP TABLE `pgr_projects`;--> statement-breakpoint
DROP TABLE `psychosocial_applications`;--> statement-breakpoint
DROP TABLE `psychosocial_responses`;--> statement-breakpoint
DROP TABLE `psychosocial_results`;--> statement-breakpoint
DROP TABLE `sst_occurrences`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `support_tickets`;--> statement-breakpoint
DROP TABLE `trainings`;--> statement-breakpoint
DROP TABLE `workspace_members`;