import { BookMarked, ExternalLink, FileText, Search, ShieldCheck } from "lucide-react";
import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";

const libraryItems = [
  { title: "NR-01 — Disposições Gerais e Gerenciamento de Riscos", kind: "Norma", description: "Página oficial da NR-01, que reúne o texto vigente e instrumentos de orientação para GRO e PGR.", url: "https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1" },
  { title: "NR-06 — Equipamento de Proteção Individual", kind: "Norma", description: "Página oficial da NR-06 com o texto normativo e referências sobre equipamentos de proteção individual.", url: "https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-6-nr-6" },
  { title: "Perguntas e respostas sobre GRO e PGR", kind: "Orientação", description: "Material oficial de perguntas e respostas sobre o capítulo de gerenciamento de riscos da NR-01.", url: "https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/PerguntaseRespostasGROPGRMaio2026.pdf" },
  { title: "Manual de interpretação e aplicação da NR-01", kind: "Manual", description: "Manual oficial de interpretação e aplicação do capítulo 1.5 da NR-01, voltado ao GRO e PGR.", url: "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/manuais-e-publicacoes/manual_gro_pgr_da_nr_1.pdf/" },
];

export default function Library() {
  const { loading } = useAuth({ redirectOnUnauthenticated: true });
  const [term, setTerm] = useState("");
  const filtered = libraryItems.filter(item => `${item.title} ${item.kind} ${item.description}`.toLocaleLowerCase("pt-BR").includes(term.toLocaleLowerCase("pt-BR")));
  if (loading) return null;
  return <DashboardLayout title="Biblioteca"><div className="mx-auto max-w-6xl"><section className="overflow-hidden rounded-[2rem] bg-[#063b43] p-7 text-white shadow-lg md:p-9"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8edec7]">Base técnica compartilhada</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Conteúdo técnico em fontes oficiais, reunido para a rotina do TST.</h2><p className="mt-4 text-sm leading-6 text-[#c5e2dc]">A Biblioteca começa com referências oficiais do Ministério do Trabalho e Emprego. Os links são abertos em nova aba para preservar a fonte e sua versão publicada.</p></div><div className="mt-7 max-w-xl"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#749e97]" /><Input value={term} onChange={event => setTerm(event.target.value)} placeholder="Pesquisar normas e orientações" className="h-12 rounded-xl border-white/15 bg-white text-[#102b32] pl-11" /></div></div></section><section className="mt-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#0c8c89]">Fontes oficiais</p><h3 className="mt-1 text-2xl font-bold">Referências essenciais para o PGR</h3></div><span className="hidden rounded-full bg-[#e8f6f1] px-3 py-1 text-xs font-bold text-[#0c7474] md:block">{filtered.length} materiais</span></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <article key={item.title} className="rounded-2xl border border-[#dcebe8] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f6f1] text-[#0c7474]">{item.kind === "Norma" ? <BookMarked className="h-5 w-5" /> : item.kind === "Manual" ? <ShieldCheck className="h-5 w-5" /> : <FileText className="h-5 w-5" />}</span><span className="rounded-full bg-[#f3f8f7] px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-[#668087]">{item.kind}</span></div><h4 className="mt-5 text-lg font-bold leading-6">{item.title}</h4><p className="mt-2 text-sm leading-6 text-[#668087]">{item.description}</p><a href={item.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#0c7474]"><ExternalLink className="h-4 w-4" />Abrir fonte oficial</a></article>)}</div>{filtered.length === 0 && <div className="mt-5 rounded-2xl border border-dashed border-[#bddbd5] bg-white p-8 text-center text-sm text-[#668087]">Nenhum material encontrado para a busca atual.</div>}</section></div></DashboardLayout>;
}
