import { useMemo, useState } from "react";
import { ExternalLink, PlayCircle, Search, Tags, Video, X } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export default function Videos() {
  const videosQuery = trpc.videos.published.useQuery();
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("Todos");
  const videos = videosQuery.data ?? [];
  const categories = useMemo(() => ["Todos", ...Array.from(new Set(videos.map(video => video.category))).sort((a, b) => a.localeCompare(b, "pt-BR"))], [videos]);
  const filteredVideos = useMemo(() => {
    const term = search.trim().toLocaleLowerCase("pt-BR");
    return videos.filter(video => {
      const content = `${video.title} ${video.description} ${video.category}`.toLocaleLowerCase("pt-BR");
      return (category === "Todos" || video.category === category) && (!term || content.includes(term));
    });
  }, [category, search, videos]);

  return <DashboardLayout title="Vídeos do canal"><div className="mx-auto max-w-7xl space-y-7">
    <section className="relative overflow-hidden rounded-[2rem] bg-[linear-gradient(120deg,#063b43_0%,#0c7474_55%,#174d71_100%)] px-6 py-8 text-white shadow-[0_22px_52px_rgba(7,59,67,.17)] lg:px-9 lg:py-10"><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-[#f63b35]/25 blur-3xl" /><div className="pointer-events-none absolute -bottom-28 left-1/3 h-60 w-60 rounded-full bg-[#8edec7]/15 blur-3xl" /><div className="relative grid gap-6 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] text-[#d8f4ea]"><Video className="h-3.5 w-3.5" /> Canal TST Brasil Hub</span><h1 className="mt-4 max-w-2xl font-display text-3xl font-bold tracking-tight sm:text-4xl">Conteúdos em vídeo para apoiar sua rotina de SST.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c8e6df]">Assista aos vídeos publicados no canal oficial do YouTube sem armazenar arquivos pesados no portal. Cada miniatura abre o vídeo na plataforma do canal.</p></div><div className="grid grid-cols-2 gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 backdrop-blur-sm"><div><p className="text-3xl font-bold text-white">{videos.length}</p><p className="mt-1 text-[11px] font-medium text-[#c4e2da]">vídeos publicados</p></div><div><p className="text-3xl font-bold text-white">{categories.length - 1}</p><p className="mt-1 text-[11px] font-medium text-[#c4e2da]">temas disponíveis</p></div></div></div></section>

    <section className="rounded-[1.5rem] border border-[#dcebe8] bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#6e8c88]" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Busque por tema, NR, CIPA, EPI ou treinamento..." className="h-11 rounded-xl border-[#d6e8e3] bg-[#fbfefd] pl-10 text-sm" /></div>{(search || category !== "Todos") && <Button type="button" variant="outline" onClick={() => { setSearch(""); setCategory("Todos"); }} className="h-11 shrink-0 rounded-xl border-[#d3e5e0] text-xs font-bold text-[#397069]"><X className="mr-1.5 h-3.5 w-3.5" />Limpar</Button>}</div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-[#edf4f1] pt-4"><span className="inline-flex items-center gap-1 text-[11px] font-bold uppercase tracking-[.12em] text-[#668087]"><Tags className="h-3.5 w-3.5" /> Temas</span>{categories.map(item => <button key={item} type="button" onClick={() => setCategory(item)} className={`rounded-lg px-3 py-2 text-xs font-bold transition ${category === item ? "bg-[#0c7474] text-white" : "bg-[#edf7f3] text-[#397069] hover:bg-[#d9eee7]"}`}>{item}</button>)}</div><p className="mt-4 text-xs font-medium text-[#668087]">{filteredVideos.length} {filteredVideos.length === 1 ? "vídeo encontrado" : "vídeos encontrados"}</p></section>

    {videosQuery.isLoading ? <section className="grid min-h-64 place-items-center rounded-[1.5rem] border border-[#dcebe8] bg-white text-sm font-semibold text-[#668087]">Carregando vídeos publicados...</section> : filteredVideos.length ? <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filteredVideos.map(video => <article key={video.id} className="group overflow-hidden rounded-[1.75rem] border border-[#dcebe8] bg-white shadow-[0_12px_34px_rgba(16,43,50,.06)] transition hover:-translate-y-1 hover:border-[#7ebfb1] hover:shadow-[0_20px_44px_rgba(16,43,50,.12)]"><a href={video.youtubeUrl} target="_blank" rel="noreferrer" className="relative block aspect-video overflow-hidden bg-[#073b43]"><img src={video.thumbnailUrl} alt={`Miniatura: ${video.title}`} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.04]" /><span className="absolute inset-0 bg-gradient-to-t from-[#052f36]/65 via-transparent to-transparent" /><span className="absolute bottom-3 left-3 grid h-11 w-11 place-items-center rounded-full bg-[#f3322b] text-white shadow-lg"><PlayCircle className="h-6 w-6" /></span>{video.featured && <span className="absolute right-3 top-3 rounded-full bg-[#fff0c9] px-2.5 py-1 text-[10px] font-bold text-[#9a6412]">Em destaque</span>}</a><div className="p-5"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-[#0c7474]">{video.category}</p><h2 className="mt-2 text-lg font-bold tracking-tight text-[#102b32]">{video.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-5 text-[#668087]">{video.description}</p><Button asChild className="mt-5 h-10 w-full rounded-xl bg-[#0c7474] text-xs font-bold text-white hover:bg-[#063b43]"><a href={video.youtubeUrl} target="_blank" rel="noreferrer">Assistir no YouTube <ExternalLink className="ml-2 h-4 w-4" /></a></Button></div></article>)}</section> : <section className="rounded-[1.75rem] border border-dashed border-[#badbd2] bg-white px-6 py-16 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e8f6f1] text-[#0c7474]"><Video className="h-7 w-7" /></span><h2 className="mt-4 text-xl font-bold text-[#102b32]">{videos.length ? "Nenhum vídeo corresponde à sua busca" : "Vídeos em preparação"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#668087]">{videos.length ? "Experimente outro tema ou termo de pesquisa." : "O Administrador Mestre publicará aqui os próximos vídeos do canal oficial do TST Brasil Hub."}</p></section>}
  </div></DashboardLayout>;
}
