export const publicAssetUrls = {
  logo: "/assets/tst-logo.png",
  favicon: "/assets/tst-favicon.png",
  hero: "/assets/tst-hero.jpg",
  watermarkNr05: "/assets/watermark-nr05.jpg",
  watermarkNr10: "/assets/watermark-nr10.jpg",
  watermarkNr15: "/assets/watermark-nr15.jpg",
  watermarkNr20: "/assets/watermark-nr20.jpg",
  watermarkNr33: "/assets/watermark-nr33.jpg",
  watermarkNr35: "/assets/watermark-nr35.jpg",
  watermarkNr01: "/assets/watermark-nr01.jpg",
  watermarkNr06: "/assets/watermark-nr06.jpg",
  watermarkNr17: "/assets/watermark-nr17.jpg",
  watermarkNr18: "/assets/watermark-nr18.jpg",
  watermarkNr23: "/assets/watermark-nr23.jpg",
  watermarkNrEquipment: "/assets/watermark-nr-equipment.jpg",
  pgrLegacyHtml: "/assets/pgr-legacy.html",
} as const;

export const legacyPublicAssetUrls: Record<string, string> = {
  "tst-brasil-hub-logo-otimizado_50d81e90.png": publicAssetUrls.logo,
  "tst-brasil-hub-favicon_07785ba1.png": publicAssetUrls.favicon,
  "tst-hub-hero-seguranca_e69cb11f.jpg": publicAssetUrls.hero,
  "certificate-watermark-nr05_c09495dd.jpg": publicAssetUrls.watermarkNr05,
  "certificate-watermark-nr10_b040e9df.jpg": publicAssetUrls.watermarkNr10,
  "certificate-watermark-nr15_552a2d54.jpg": publicAssetUrls.watermarkNr15,
  "certificate-watermark-nr20_db15a211.jpg": publicAssetUrls.watermarkNr20,
  "certificate-watermark-nr33_6aa5caf5.jpg": publicAssetUrls.watermarkNr33,
  "certificate-watermark-nr35_3d8a561b.jpg": publicAssetUrls.watermarkNr35,
  "certificate-watermark-nr01_469fac80.jpg": publicAssetUrls.watermarkNr01,
  "certificate-watermark-nr06_16be9632.jpg": publicAssetUrls.watermarkNr06,
  "certificate-watermark-nr17_1123a518.jpg": publicAssetUrls.watermarkNr17,
  "certificate-watermark-nr18_5377cf1a.jpg": publicAssetUrls.watermarkNr18,
  "certificate-watermark-nr23_e9c95ca7.jpg": publicAssetUrls.watermarkNr23,
  "certificate-watermark-nr11_9b136328.jpg":
    publicAssetUrls.watermarkNrEquipment,
};
