import mysql from "mysql2/promise";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  console.log(
    "[migrate:baseline] DATABASE_URL não configurada; migração ignorada neste ambiente."
  );
  process.exit(0);
}

const connection = await mysql.createConnection(databaseUrl);

const statements = [
  `CREATE TABLE IF NOT EXISTS admin_access_audit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    targetUserId INT NOT NULL,
    adminUserId INT NOT NULL,
    action ENUM('renew','suspend','reactivate','disable') NOT NULL,
    previousStatus VARCHAR(64) NULL,
    nextStatus VARCHAR(64) NULL,
    previousExpiresAt TIMESTAMP NULL,
    nextExpiresAt TIMESTAMP NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX admin_access_audit_target_idx (targetUserId, createdAt),
    INDEX admin_access_audit_admin_idx (adminUserId, createdAt)
  )`,
  `CREATE TABLE IF NOT EXISTS certificates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NULL,
    category ENUM('certificate','pgr','ltcat','os','pcmat','laudo','other') NOT NULL DEFAULT 'certificate',
    participantName VARCHAR(255) NOT NULL,
    trainingName VARCHAR(255) NOT NULL,
    issuedAt TIMESTAMP NOT NULL,
    expiresAt TIMESTAMP NULL,
    referenceUrl VARCHAR(2048) NULL,
    notes VARCHAR(1500) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX certificates_workspace_idx (workspaceId),
    INDEX certificates_company_idx (companyId),
    INDEX certificates_category_idx (workspaceId, category)
  )`,
  `CREATE TABLE IF NOT EXISTS cipa_commissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    status ENUM('planning','election','active','archived') NOT NULL DEFAULT 'planning',
    riskLevel INT NOT NULL,
    employeeCount INT NOT NULL,
    city VARCHAR(160) NULL,
    workplace VARCHAR(255) NULL,
    unionName VARCHAR(255) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY cipa_commissions_workspace_company_unique (workspaceId, companyId),
    INDEX cipa_commissions_workspace_idx (workspaceId, status),
    INDEX cipa_commissions_company_idx (companyId)
  )`,
  `CREATE TABLE IF NOT EXISTS cipa_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commissionId INT NOT NULL,
    termId INT NOT NULL,
    workspaceId INT NOT NULL,
    type ENUM('election_committee','union_notice','notice','registration','ballot','election_minutes','possession_minutes','work_plan') NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    companyLogoUrl VARCHAR(2048) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX cipa_documents_term_idx (termId, createdAt),
    INDEX cipa_documents_workspace_idx (workspaceId, type)
  )`,
  `CREATE TABLE IF NOT EXISTS cipa_meetings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commissionId INT NOT NULL,
    termId INT NOT NULL,
    workspaceId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    meetingType ENUM('ordinary','extraordinary') NOT NULL DEFAULT 'ordinary',
    scheduledAt TIMESTAMP NOT NULL,
    location VARCHAR(255) NULL,
    agenda VARCHAR(2000) NULL,
    minutesSummary VARCHAR(4000) NULL,
    status ENUM('scheduled','completed','cancelled') NOT NULL DEFAULT 'scheduled',
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX cipa_meetings_term_schedule_idx (termId, scheduledAt),
    INDEX cipa_meetings_workspace_schedule_idx (workspaceId, scheduledAt)
  )`,
  `CREATE TABLE IF NOT EXISTS cipa_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commissionId INT NOT NULL,
    termId INT NOT NULL,
    workspaceId INT NOT NULL,
    employeeId INT NOT NULL,
    role ENUM('election_committee','candidate','employer_representative','employee_representative') NOT NULL,
    \`condition\` ENUM('titular','suplente','not_applicable') NOT NULL DEFAULT 'not_applicable',
    voteCount INT NOT NULL DEFAULT 0,
    status ENUM('active','withdrawn','elected','not_elected') NOT NULL DEFAULT 'active',
    notes VARCHAR(1000) NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY cipa_members_term_employee_role_unique (termId, employeeId, role),
    INDEX cipa_members_term_idx (termId, role, status),
    INDEX cipa_members_workspace_idx (workspaceId, employeeId)
  )`,
  `CREATE TABLE IF NOT EXISTS cipa_terms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    commissionId INT NOT NULL,
    workspaceId INT NOT NULL,
    label VARCHAR(64) NOT NULL,
    enrollmentStartsAt TIMESTAMP NULL,
    electionAt TIMESTAMP NULL,
    possessionAt TIMESTAMP NULL,
    endsAt TIMESTAMP NULL,
    status ENUM('planning','election','active','closed') NOT NULL DEFAULT 'planning',
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY cipa_terms_commission_label_unique (commissionId, label),
    INDEX cipa_terms_workspace_idx (workspaceId, status),
    INDEX cipa_terms_commission_idx (commissionId, updatedAt)
  )`,
  `CREATE TABLE IF NOT EXISTS client_engagements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    status ENUM('lead','active','inactive') NOT NULL DEFAULT 'lead',
    nextFollowUpAt TIMESTAMP NULL,
    notes VARCHAR(1500) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY client_engagements_company_unique (companyId),
    INDEX client_engagements_workspace_idx (workspaceId),
    INDEX client_engagements_status_idx (workspaceId, status),
    INDEX client_engagements_follow_up_idx (workspaceId, nextFollowUpAt)
  )`,
  `CREATE TABLE IF NOT EXISTS client_visits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    scheduledAt TIMESTAMP NOT NULL,
    objective VARCHAR(500) NOT NULL,
    notes VARCHAR(1500) NULL,
    status ENUM('planned','completed','cancelled') NOT NULL DEFAULT 'planned',
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX client_visits_workspace_idx (workspaceId),
    INDEX client_visits_company_idx (companyId),
    INDEX client_visits_status_idx (workspaceId, status),
    INDEX client_visits_scheduled_idx (workspaceId, scheduledAt)
  )`,
  `CREATE TABLE IF NOT EXISTS content_materials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    placement ENUM('marketplace','library') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    format ENUM('modelo','planilha','checklist','ebook','curso','documento','outro') NOT NULL DEFAULT 'outro',
    salePlatform ENUM('hotmart','kiwify','externo','nenhuma') NOT NULL DEFAULT 'nenhuma',
    priceCents INT NULL,
    referenceUrl VARCHAR(2048) NULL,
    coverUrl VARCHAR(2048) NULL,
    fileUrl VARCHAR(2048) NULL,
    fileName VARCHAR(255) NULL,
    fileMimeType VARCHAR(120) NULL,
    status ENUM('draft','published','hidden') NOT NULL DEFAULT 'draft',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    createdByUserId INT NOT NULL,
    publishedAt TIMESTAMP NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX content_materials_public_idx (placement, status, featured),
    INDEX content_materials_updated_idx (updatedAt)
  )`,
  `CREATE TABLE IF NOT EXISTS content_material_clicks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    materialId INT NOT NULL,
    userId INT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX content_material_clicks_material_created_idx (materialId, createdAt),
    INDEX content_material_clicks_user_created_idx (userId, createdAt)
  )`,
  `CREATE TABLE IF NOT EXISTS departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX departments_workspace_idx (workspaceId),
    INDEX departments_company_idx (companyId),
    UNIQUE KEY departments_company_name_unique (companyId, name)
  )`,
  `CREATE TABLE IF NOT EXISTS epi_returns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    deliveryId INT NULL,
    epiItemId INT NOT NULL,
    employeeId INT NOT NULL,
    returnedAt TIMESTAMP NOT NULL,
    \`condition\` ENUM('good','damaged','expired','lost') NOT NULL,
    notes VARCHAR(1000) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX epi_returns_workspace_idx (workspaceId),
    INDEX epi_returns_company_idx (companyId),
    INDEX epi_returns_employee_idx (workspaceId, employeeId)
  )`,
  `CREATE TABLE IF NOT EXISTS inspection_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    departmentId INT NULL,
    name VARCHAR(255) NOT NULL,
    riskType VARCHAR(120) NOT NULL,
    routineType VARCHAR(120) NOT NULL,
    description VARCHAR(1500) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX inspection_templates_workspace_idx (workspaceId),
    INDEX inspection_templates_company_idx (companyId),
    INDEX inspection_templates_department_idx (departmentId),
    INDEX inspection_templates_active_idx (workspaceId, active)
  )`,
  `CREATE TABLE IF NOT EXISTS inspection_template_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    templateId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    guidance VARCHAR(1000) NULL,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    sortOrder INT NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX inspection_template_items_workspace_idx (workspaceId),
    INDEX inspection_template_items_template_idx (templateId, sortOrder)
  )`,
  `CREATE TABLE IF NOT EXISTS job_roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    departmentId INT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX job_roles_workspace_idx (workspaceId),
    INDEX job_roles_company_idx (companyId),
    INDEX job_roles_department_idx (departmentId),
    UNIQUE KEY job_roles_company_department_name_unique (companyId, departmentId, name)
  )`,
  `CREATE TABLE IF NOT EXISTS materials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    category ENUM('modelo','checklist','procedimento','outro') NOT NULL DEFAULT 'outro',
    description VARCHAR(1500) NULL,
    referenceUrl VARCHAR(2048) NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX materials_workspace_idx (workspaceId)
  )`,
  `CREATE TABLE IF NOT EXISTS pgr_projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NULL,
    name VARCHAR(255) NOT NULL,
    legacyStorageKey VARCHAR(255) NOT NULL,
    consultancyName VARCHAR(255) NULL,
    consultancyLogoUrl VARCHAR(2048) NULL,
    riskMapImageUrl VARCHAR(2048) NULL,
    visualMatrixImageUrl VARCHAR(2048) NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY pgr_projects_legacyStorageKey_unique (legacyStorageKey),
    INDEX pgr_projects_workspace_idx (workspaceId)
  )`,
  `CREATE TABLE IF NOT EXISTS pgr_revisions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pgrProjectId INT NOT NULL,
    workspaceId INT NOT NULL,
    companyId INT NULL,
    versionNumber VARCHAR(32) NOT NULL,
    revisionSummary TEXT NOT NULL,
    changesDescription TEXT NOT NULL,
    sectionObservations TEXT NULL,
    documentSnapshot TEXT NULL,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX pgr_revisions_project_idx (pgrProjectId),
    INDEX pgr_revisions_workspace_idx (workspaceId)
  )`,
  `CREATE TABLE IF NOT EXISTS pgr_technical_signatures (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pgrProjectId INT NOT NULL,
    workspaceId INT NOT NULL,
    professionalName VARCHAR(255) NOT NULL,
    professionalRole VARCHAR(128) NOT NULL DEFAULT 'Técnico em Segurança do Trabalho',
    professionalRegistry VARCHAR(64) NOT NULL,
    signatureDate TIMESTAMP NOT NULL,
    digitalStampCode VARCHAR(128) NOT NULL,
    signatureImageUrl VARCHAR(2048) NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY pgr_technical_signatures_pgrProjectId_unique (pgrProjectId),
    INDEX pgr_signatures_project_idx (pgrProjectId)
  )`,
  `CREATE TABLE IF NOT EXISTS pgr_attachments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pgrProjectId INT NOT NULL,
    workspaceId INT NOT NULL,
    title VARCHAR(128) NOT NULL,
    category ENUM('photo','laudo','art','certificate','other') NOT NULL DEFAULT 'photo',
    fileKey VARCHAR(512) NOT NULL,
    fileUrl VARCHAR(2048) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX pgr_attachments_project_idx (pgrProjectId),
    INDEX pgr_attachments_workspace_idx (workspaceId)
  )`,
  `CREATE TABLE IF NOT EXISTS psychosocial_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    departmentId INT NULL,
    title VARCHAR(255) NOT NULL,
    status ENUM('draft','active','completed') NOT NULL DEFAULT 'active',
    minRespondents INT NOT NULL DEFAULT 10,
    respondentCount INT NOT NULL DEFAULT 0,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX psychosocial_applications_workspace_idx (workspaceId),
    INDEX psychosocial_applications_company_idx (companyId)
  )`,
  `CREATE TABLE IF NOT EXISTS psychosocial_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    applicationId INT NOT NULL,
    respondentHash VARCHAR(128) NOT NULL,
    answersJson VARCHAR(4000) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX psychosocial_responses_app_idx (applicationId)
  )`,
  `CREATE TABLE IF NOT EXISTS psychosocial_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    applicationId INT NOT NULL,
    dimensionKey VARCHAR(64) NOT NULL,
    dimensionName VARCHAR(255) NOT NULL,
    domainName VARCHAR(255) NOT NULL,
    score INT NOT NULL,
    riskLevel ENUM('low','medium','high') NOT NULL,
    exportedToPgr BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX psychosocial_results_app_idx (applicationId),
    INDEX psychosocial_results_risk_idx (applicationId, riskLevel)
  )`,
  `CREATE TABLE IF NOT EXISTS sst_occurrences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NOT NULL,
    departmentId INT NULL,
    employeeId INT NULL,
    type ENUM('near_miss','incident','accident') NOT NULL,
    occurredAt TIMESTAMP NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    status ENUM('open','under_review','closed') NOT NULL DEFAULT 'open',
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX sst_occurrences_workspace_idx (workspaceId),
    INDEX sst_occurrences_company_idx (companyId),
    INDEX sst_occurrences_status_idx (workspaceId, status),
    INDEX sst_occurrences_occurred_at_idx (workspaceId, occurredAt)
  )`,
  `CREATE TABLE IF NOT EXISTS support_tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    status ENUM('open','in_progress','resolved') NOT NULL DEFAULT 'open',
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX support_tickets_workspace_idx (workspaceId)
  )`,
  `CREATE TABLE IF NOT EXISTS trainings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspaceId INT NOT NULL,
    companyId INT NULL,
    title VARCHAR(255) NOT NULL,
    status ENUM('planned','completed') NOT NULL DEFAULT 'planned',
    scheduledAt TIMESTAMP NULL,
    scheduledDatesJson TEXT NULL,
    instructorName VARCHAR(255) NULL,
    location VARCHAR(255) NULL,
    participantCount INT NOT NULL DEFAULT 0,
    createdByUserId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX trainings_workspace_idx (workspaceId),
    INDEX trainings_company_idx (companyId)
  )`,
  `CREATE TABLE IF NOT EXISTS training_participants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    trainingId INT NOT NULL,
    workspaceId INT NOT NULL,
    employeeId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY training_participants_training_employee_unique (trainingId, employeeId),
    INDEX training_participants_workspace_idx (workspaceId, trainingId),
    INDEX training_participants_employee_idx (workspaceId, employeeId)
  )`,
  `CREATE TABLE IF NOT EXISTS youtube_videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1500) NOT NULL,
    category VARCHAR(100) NOT NULL,
    youtubeUrl VARCHAR(2048) NOT NULL,
    youtubeVideoId VARCHAR(32) NOT NULL,
    thumbnailUrl VARCHAR(2048) NOT NULL,
    status ENUM('draft','published','hidden') NOT NULL DEFAULT 'draft',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    createdByUserId INT NOT NULL,
    publishedAt TIMESTAMP NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY youtube_videos_video_id_unique (youtubeVideoId),
    INDEX youtube_videos_public_idx (status, featured, publishedAt),
    INDEX youtube_videos_updated_idx (updatedAt)
  )`,
];

try {
  for (const statement of statements) await connection.execute(statement);
  console.log(
    `[migrate:baseline] ${statements.length} tabelas-base verificadas.`
  );
} finally {
  await connection.end();
}
